services:
  - type: web
    name: eonveil-room-system
    env: node
    buildCommand: cd eonveil-room-system && npm install
    startCommand: cd eonveil-room-system && node server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3001
